---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-pvs-sap
    kind: solution
    catalog_id: da12d6f3-3cb7-402e-9350-878837212a6e
    offering_id: 9aa6135e-75d5-467e-9f4a-ac2a21c069b8
    variations:
      - name: sap-ready-to-go
        mark_ready: false
        install_type: extension
        import_only: true
      - name: sap-s4hana-bw4hana
        mark_ready: false
        install_type: extension
        import_only: true
