version: "v1"
CRA_TARGETS:
  - CRA_TARGET: "solutions/basic"
    PROFILE_ID: "0e6e7b5a-817d-4344-ab6f-e5d7a9c49520" # SCC profile ID (currently set to the FSCloud 1.4.0 profile).
    CRA_IGNORE_RULES_FILE: "cra-tf-validate-ignore-rules.json"
    CRA_ENVIRONMENT_VARIABLES:
      TF_VAR_prefix: "cra-infra"
      TF_VAR_powervs_zone: "syd05"
      TF_VAR_powervs_resource_group_name: "Default"
      TF_VAR_powervs_workspace_name: "powervs-workspace"
