- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true

  vars:
    sap_swpm_ansible_role_mode: default

  tasks:
    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_install_media_detect }

    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_swpm }

    - name: SAP SWPM Post Install - Enforce Connection Info in hdbuserstore
      ansible.builtin.shell: "runuser -l {{sap_swpm_sid|lower}}adm -c 'hdbuserstore SET DEFAULT {{ sap_swpm_db_host }}:3{{ sap_swpm_db_instance_nr }}13 {{ sap_swpm_db_schema_abap }} '{{ sap_swpm_db_system_password }}"
      when: sap_swpm_install_saphostagent
